#include "alsa/asoundlib.h"

#define ALSA_DEV_DEFAULT "plughw:0,0"
#define ALSA_LATENCY_DEFAULT 13230
#define ALSA_FRAGMENT_SIZE 2205
#define ALSA_FRAGMENT_SIZE_MAX 22050
#define ALSA_PERIOD 10
#define ALSA_FORMAT_DEFAULT SND_PCM_FORMAT_S16_LE
#define ALSA_ACCESS_DEFAULT SND_PCM_ACCESS_RW_INTERLEAVED
